base/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.getRoutes),
    path('rooms', views.getRooms),
    path('room/<int:id>', views.getRoom),
    
    
]

base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login',views.loginPage,name="login"),
    path('logout',views.logoutUser,name="logout"),
    path('register',views.registerUser,name="register"),

    path('',views.home,name="home"),
    path('room/<int:pk>/',views.room,name="room"),
    path('profile/<int:pk>/',views.userProfile,name="user-profile"),
    path('topics/',views.topicsPage,name="topics"),
    path('activity/',views.activityPage,name="activity"),
    
    path('create-room',views.createRoom, name="create-room"),
    path('update-room/<int:pk>/',views.updateRoom, name="update-room"),
    path('delete-room/<int:pk>/',views.deleteRoom, name="delete-room"),
    path('delete-message/<int:pk>/',views.deleteMessage, name="delete-message"),
    
    path('update-user/',views.updateUser, name="update-user"),
    
    #follow-topic
    path('follow_topic/<int:topic_id>',views.followTopic,name="follow-topic"),

    #follow-user
    path('follow_user/<int:user_id>',views.followUser,name="follow-user")
]

studybud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length=200,null=True)
    email = models.EmailField(unique=True,null=True)
    bio = models.TextField(null=True,blank=True)
    avatar = models.ImageField(null=True,default='avatar.svg')
    followers = models.ManyToManyField('User',blank=True,related_name="followings_info")
    followings = models.ManyToManyField('User',blank=True,related_name="followers_info")

    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS  = []

class Topic(models.Model):
    name = models.CharField(max_length=200)
    followers = models.ManyToManyField(User,blank=True,related_name="followedtopics")
    
    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='hostedrooms')
    topic = models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    participants = models.ManyToManyField(User,blank=True,related_name='joinedrooms')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-updated','-created']

    def __str__(self):
        return self.name
    
class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="usermessages")
    room = models.ForeignKey(Room,on_delete=models.CASCADE,related_name="messages")
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-updated','-created']

    def __str__(self):
        return self.body[0:50]
    

base/forms.py
from django.forms import ModelForm
from .models import Room, User
from django.contrib.auth.forms import UserCreationForm

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name','username','email','password1','password2']

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host','participants']
        
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar','name','username','email','bio']

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .serializers import RoomSerializer
from base.models import Room


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/room/:id',
    ]
    
    return Response(routes)

@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializedrooms = RoomSerializer(rooms, many=True)   

    return Response(serializedrooms.data)

@api_view(['GET'])
def getRoom(request,id):
    room = Room.objects.get(id=id)
    serializedroom = RoomSerializer(room, many=False)   

    return Response(serializedroom.data)

base/views.py
import json
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt


from .models import  Message, Room, Topic
from .forms import RoomForm, UserForm, User,MyUserCreationForm

# Create your views here.

def loginPage(request):
    if request.method == 'POST':
        email = request.POST["email"].lower()
        password = request.POST["password"]
        
        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request,"User does not exist")

        user = authenticate(email=email,password=password)
        if not user:
            messages.error(request,"Email or Password is incorrect")
        else:
            login(request,user)
            return redirect("home")
        
    if request.user.is_authenticated:
        return redirect('home')
    page = 'login'
    return render(request,'base/login_register.html', {'page': page})

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerUser(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.add_message(request,messages.ERROR,"An error occurred during registration.")

    return render(request,'base/login_register.html',{'form': form})

def home(request):
    q = request.GET.get("q") if request.GET.get("q") else ""
    page = request.GET.get('page') if request.GET.get('page') else ""
    rooms = Room.objects.filter(
        Q(topic__name__icontains = q) |
        Q(name__icontains = q) |
        Q(description__icontains = q)
    )
    paginator = Paginator(rooms, 10)
    roomsobj = paginator.get_page(page)

    topics = Topic.objects.all()[0:5]
    roomcount = rooms.count()
    page_range = int((roomcount-1)/10) 
    if page != "":
        range_start = 1 if int(page) <= 5 else int(page)
    else:
        range_start = 1
        
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    
    context = {'rooms': roomsobj,'topics':topics,'roomcount': roomcount,'room_messages': room_messages,'range': range(range_start,page_range+2)}
    return render(request,'base/home.html', context)

def room(request,pk):
    room = Room.objects.get(id=pk)
    room_messages = room.messages.all()[0:25]
    participants = room.participants.all()
    
    if request.method == 'POST':
        if request.POST.get('body'):
            message = Message.objects.create(
                user = request.user,
                room = room,
                body = request.POST['body']
            )
            message.save()
            room.participants.add(request.user)
            return redirect('room', pk=room.id)

        elif request.POST.get('edit'):
            message_id = int(request.POST['edit'])
            context = {'room': room,'room_messages': room_messages,'participants': participants,'editmessage': message_id}
            return render(request,'base/room.html',context)
        
        elif request.POST.get('newmessage'):
            message_id = request.POST['message_id']
            newmessage = request.POST['newmessage']
            message = Message.objects.get(pk=message_id)
            message.body = newmessage
            message.save()
            return redirect('room', pk=room.id)
    

    context = {'room': room,'room_messages': room_messages,'participants': participants}
    return render(request,'base/room.html', context)

def userProfile(request,pk):
    page = request.GET.get('page') if request.GET.get('page') else 1

    user = User.objects.get(pk=pk)
    rooms = user.hostedrooms.all()
    room_messages = user.usermessages.all()

    paginator = Paginator(rooms, 10)
    roomsobj = paginator.get_page(page)

    topics = Topic.objects.all()[0:5]
    roomcount = rooms.count()
    page_range = int((roomcount-1)/10) 
    if page != "":
        range_start = 1 if int(page) <= 5 else int(page)
    else:
        range_start = 1

    context = {'user': user,'rooms': roomsobj,'room_messages': room_messages,'topics': topics,'range': range(range_start,page_range+2),'roomcount': roomcount}
    return render(request,'base/profile.html', context)

@login_required(login_url='/login')
def createRoom(request):
    form = RoomForm()
    topics = Topic.objects.all()

    if request.method == 'POST':
        topic_name = request.POST['topic']
        topic, created = Topic.objects.get_or_create(
            name=topic_name
        )
        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST['name'],
            description = request.POST['description']
        )
        return redirect('home')

    context = {'form': form,'topics':topics}
    return render(request,'base/room_form.html', context)

@login_required(login_url='/login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()

    if request.user != room.host:
        return HttpResponse('You are not allowed here!')

    if request.method == "POST":
        print('updating')
        topic_name = request.POST['topic']
        topic, created = Topic.objects.get_or_create(
            name=topic_name
        )
        room.name = request.POST['name']
        room.topic = topic
        if request.POST['description'] != '':
            room.description = request.POST['description']
        room.save()
        return redirect('home')
        
    context = {'form': form,'topics': topics,'room':room}
    return render(request,'base/room_form.html',context)

@login_required(login_url='/login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse('You are not allowed here!')

    if request.method == 'POST':
        room.delete()
        return redirect('home')
    
    return render(request,'base/delete.html',{'obj': room})
    
@login_required(login_url='/login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('You are not allowed here!')

    if request.method == 'POST':
        message.delete()
        return redirect('home')
    
    return render(request,'base/delete.html',{'obj': message})

@login_required(login_url=('/login'))
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)
    
    if request.method == 'POST':
        print('updating')
        try:
            form = UserForm(request.POST, request.FILES ,instance=user)
        except:
            return render(request,'base/update-user.html',{'form': form})
        if form.is_valid():
            print('valid')
            form.save()
            return redirect('user-profile',pk=user.id)
    
    return render(request,'base/update-user.html',{'form': form})

def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') else ''
    topics = Topic.objects.filter(name__icontains = q)
    
    return render(request,'base/topics.html',{'topics': topics})

def activityPage(request):
    room_messages = Message.objects.all()

    return render(request,'base/activity.html',{'room_messages': room_messages})


def followTopic(request,topic_id):
    if request.method == 'PUT':
        data = json.loads(request.body)

        if not request.user.is_authenticated:
            return JsonResponse({"error":f"you must be logged in to {data['method']} topic"})

        topic = Topic.objects.get(id=topic_id)

        if data['method'] == "follow":
            topic.followers.add(request.user)
            topic.save()
        elif data['method'] == "unfollow":
            topic.followers.remove(request.user)
            topic.save()

        return JsonResponse({"message": f"topic {topic.name} {data['method']}ed successfully"})

def followUser(request,user_id):
    if request.method == 'PUT':
        data = json.loads(request.body)
        if not request.user.is_authenticated:
            return JsonResponse({"error":f"you must be logged in to {data['method']} users"})

        followeduser = User.objects.get(id=user_id)
        followinguser = User.objects.get(id=request.user.id)

        if data['method'] == "follow":
            followeduser.followers.add(request.user)
            followinguser.followings.add(followeduser)
            followeduser.save()
            followinguser.save()
        elif data['method'] == "unfollow":
            followeduser.followers.remove(request.user)
            followinguser.followings.remove(followeduser)
            followeduser.save()
            followinguser.save()

        return JsonResponse({"message": f"user {followinguser.username} {data['method']}ed user {followeduser.username} successfulyy"})

base/templates/base/activity.html
{% extends 'main.html' %}

{% block content %}
<main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{{request.META.HTTP_REFERER}}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          <div class="activities-page layout__body">
            {% for message in room_messages %}
            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                  </div>
                  <p>
                    @{{message.user.username}}
                    <span>{{message.created|timesince}} ago</span>
                  </p>
                </a>
                {% if request.user == message.user %}
                <div class="roomListRoom__actions">
                  <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </a>
                </div>
              {% endif %}
              </div>
              <div class="activities__boxContent">
                <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room.name}}</a>”</p>
                <div class="activities__boxRoomContent">
                  {{message.body}}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </main>

    {% endblock %}

base/templates/base/activity_component.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{message.user.avatar.url}}" />
          </div>
          <p>
            @{{message.user.username}}
            <span>{{message.created|timesince}} ago</span>
          </p>
        </a>
        {% if request.user == message.user %}
        <div class="roomListRoom__actions">
          <a href="{% url 'delete-message' message.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %}
      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
        <div class="activities__boxRoomContent">
          {{message.body}}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" action="" method="post">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{obj}}"</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

base/templates/base/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{room.host.avatar.url}}" />
        </div>
        <span>Host @{{room.host.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{room.created|timesince}} ago</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{% url 'room' room.id %}">{{room.name}}</a>
      <div style="display: flex; column-gap: 0.5em;">
        {% for user in room.participants.all %}  
        <a href="{% url 'user-profile' user.id %}">
        <div class="avatar avatar--small">
            <img src="{{user.avatar.url}}" />
        </div>
        </a>
        {% endfor %}
      </div>  
    </div>
    <div class="roomListRoom__meta">
      <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>user-group</title>
          <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
          ></path>
          <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
          ></path>
          <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
          ></path>
          <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
          ></path>
        </svg>
        {{room.participants.all.count}} Joined
      </a>
      <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
  </div>
{% endfor %}
{% if rooms.has_next or roomcount > 10%}
<div class="pagination">
    <ul class="container">
        <li>
      {% if rooms.has_previous %}
        <a href="{{ request.path }}?q={{request.GET.q}}&page={{rooms.previous_page_number}}" class="btn page-link btn--sub">Previous</a>
      {% endif %}
      {% for i in range %}
        <a href="{{ request.path }}?q={{request.GET.q}}&page={{i}}" class="btn page-link btn--sub">{{i}}</a>
      {% endfor %}
      {% if rooms.has_next %}
        <a href="{{request.path}}?q={{request.GET.q}}&page={{rooms.next_page_number}}" class="btn page-link btn--sub">Next</a>
      {% endif %}
        </li>
    </ul> 
</div>
{% endif %}

base/templates/base/home.html
  {% extends 'main.html' %}
  {% block content %}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
        {% include 'base/topics_component.html' %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" action="{% url 'home' %}">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" name="q"/>
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{roomcount}} Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
          
        {% include 'base/feed_component.html' %}
          
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        
        {% include 'base/activity_component.html' %}
        <!-- Activities End -->
      </div>
    </main>
{% endblock %}

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content%}
<main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{{request.META.HTTP_REFERER}}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for topic" name="q" />
              </label>
            </form>

            <ul class="topics__list">
              <li>
                <a href="{% url 'home' %}" class="active"> All<span>{{topics.count}}</span></a>
              </li>
              {% for topic in topics %}
              <li>
                <a href="{% url 'home' %}?q={{topic.name}}" class="active">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </main>

{% endblock %}

base/templates/base/topics_component.html
<div class="topics">
  <div class="topics__header">
    <h2>Browse Topics</h2>
  </div>
  <ul class="topics__list">
    <li>
      <a href="{% url 'home' %}" class="active">All </a>
    </li>
    {% for topic in topics %}
    <li>
      <a href="{% url 'home' %}?q={{topic.name}}" >{{topic.name}} ({{topic.room_set.all.count}})
        {% if request.user in topic.followers.all %}
        <span id="follow-topic" data-id="{{topic.id}}">Following</span>
        {% else %}
        <span id="follow-topic" data-id="{{topic.id}}">Follow</span>
        {% endif %}
      </a>
    </li>
    {% endfor %}
  </ul>
  <a class="btn btn--link" href="{% url 'topics' %}">
    More
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
  </a>
</div>

base/templates/base/update-user.html
{% extends 'main.html' %}

{% block content%}
<main class="update-account layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Edit your profile</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}

          {% for field in form%}
          <div class="form__group">
            <label for="profile_pic">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}

          <div class="form__action">
            <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
            <button class="btn btn--main" type="submit">Update</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</main>
{% endblock %}